/**
 * Single icon vocabulary for the whole app. Weight and size are standardised
 * once via IconContext in main.tsx, so no component sets them ad hoc.
 */
export {
  ArrowCounterClockwiseIcon,
  ArrowSquareOutIcon,
  BellIcon,
  CalendarBlankIcon,
  CaretDownIcon,
  CaretLeftIcon,
  ChartBarIcon,
  CheckIcon,
  DotsSixVerticalIcon,
  FilmSlateIcon,
  FireIcon,
  FlagIcon,
  GearSixIcon,
  ListBulletsIcon,
  ListChecksIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  NotePencilIcon,
  PencilSimpleIcon,
  PlusIcon,
  PushPinIcon,
  RepeatIcon,
  SortAscendingIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  SunIcon,
  TextAaIcon,
  TrashIcon,
  TrayIcon,
  WarningCircleIcon,
  XIcon,
} from '@phosphor-icons/react'
